#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Fleet OS host cutover (Oakland / SF / Backup / DestrysHP)
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${FLEET_OS_HOME:-$HOME/.hermes/fleet-os}/.env"
mkdir -p "$(dirname "$ENV_FILE")"

banner "Fleet OS host cutover"

stage "Pick this machine"
say "Fleet OS needs every Tailscale host advertising into one control plane."
step "Choose the machine id for THIS host."
ask FLEET_MACHINE_ID "Machine id (oakland-mini|sf-mini|backup-mini|destrys-hp):"
case "$FLEET_MACHINE_ID" in
  oakland-mini|sf-mini|backup-mini|destrys-hp) ;;
  *) warn "Unexpected machine id; continuing anyway." ;;
esac
write_env FLEET_MACHINE_ID "$FLEET_MACHINE_ID"

stage "Attio API key"
say "Attio is the GTM source of truth. Workers need a real HTTP key for offline reconcile."
open_url "https://app.attio.com/byteport/settings/developers"
step "Open Developers → API keys (or Access tokens)."
step "Create or reveal a token that can read people + companies (writes optional)."
ask_secret ATTIO_API_KEY "Paste the Attio API key:"
write_env ATTIO_API_KEY "$ATTIO_API_KEY"
write_env FLEET_ATTIO_API_KEY "$ATTIO_API_KEY"

stage "Tailscale mesh"
say "The cloud agent cannot fake Tailscale. This host must be on the mesh."
if command -v tailscale >/dev/null 2>&1 && tailscale status >/dev/null 2>&1; then
  note "tailscale status succeeded. That is not liveFromThisHost yet."
else
  warn "tailscale not ready."
  open_url "https://login.tailscale.com/admin/machines"
  step "Install/login Tailscale on this Mac if needed, then confirm alex-mac-mini-1 is on the tailnet."
  pause "Press enter after 'tailscale status' works."
fi
write_env FLEET_TAILSCALE_MESH 0
note "bootstrap-fleet-host.sh will stamp FLEET_TAILSCALE_MESH=1 only after fleet-mesh-probe reports liveFromThisHost."

stage "Control plane URL + ledger"
say "Workers point at Oakland's fleet-server. Oakland itself hosts :8787."
if [[ "$FLEET_MACHINE_ID" == "oakland-mini" ]]; then
  write_env FLEET_OS_PORT "${FLEET_OS_PORT:-8787}"
  [[ -z "$(_existing FLEET_OS_URL || true)" ]] && write_env FLEET_OS_URL "http://127.0.0.1:8787"
else
  [[ -z "$(_existing FLEET_OS_URL || true)" ]] && write_env FLEET_OS_URL "http://oakland-mini:8787"
fi
ask FLEET_OS_URL "Oakland control plane URL:"
write_env FLEET_OS_URL "$FLEET_OS_URL"
DEFAULT_LEDGER="$HOME/Library/Application Support/agentic-os/ledger.sqlite"
if [[ -f "$DEFAULT_LEDGER" ]]; then
  write_env FLEET_LEDGER_PATH "$DEFAULT_LEDGER"
  note "Using existing agentic-os ledger: $DEFAULT_LEDGER"
else
  [[ -z "$(_existing FLEET_LEDGER_PATH || true)" ]] && write_env FLEET_LEDGER_PATH "${FLEET_OS_HOME:-$HOME/.hermes/fleet-os}/agentic-ledger.sqlite"
  ask FLEET_LEDGER_PATH "Path for agentic-os ledger sqlite:"
  write_env FLEET_LEDGER_PATH "$FLEET_LEDGER_PATH"
fi
write_env FLEET_AUTO_SYNC_LEDGER 1

stage "Bootstrap advertise daemon"
say "Install the LaunchAgent/daemon and prove readiness."
confirm "Run bootstrap-fleet-host.sh for $FLEET_MACHINE_ID now?"
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a
"$ROOT/scripts/bootstrap-fleet-host.sh" "$FLEET_MACHINE_ID"
step "Check readiness against the control plane."
curl -sS -X POST "${FLEET_OS_URL}" -H 'content-type: application/json' -d '{"action":"readiness"}' | tee /tmp/fleet-readiness.json || true
note "Ready when readyForProductionDoD is true and blockers is empty."

finish
note "Next on other machines: re-run this wizard with their machine id."
note "Oakland should keep: pnpm fleet-server --host 0.0.0.0 --port 8787"
